fix: CI GHCR waiting

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -97,11 +97,33 @@ jobs:
           cache-from: type=gha
           cache-to: type=gha,mode=max
 
+      - name: Wait for ML base image
+        if: needs.test.outputs.ml_base == 'true'
+        run: |
+          IMAGE="ghcr.io/${{ github.repository }}/recsys-ml-base:${{ env.TAG }}"
+      
+          for i in {1..10}; do
+            echo "Attempt $i: pulling $IMAGE"
+            
+            if docker pull $IMAGE; then
+              echo "Image is available!"
+              exit 0
+            fi
+      
+            echo "Not ready yet, retrying in 3s..."
+            sleep 3
+          done
+      
+          echo "Failed to pull image after retries"
+          exit 1
+
       # ML SERVICE
       - name: Build ML service
         if: needs.test.outputs.ml == 'true' || needs.test.outputs.ml_base == 'true'
         uses: docker/build-push-action@v5
         with:
+          build-args: |
+            BASE_TAG=${{ github.event_name == 'pull_request' && 'develop' || env.TAG }}
           context: ./apps/ml-service
           push: ${{ github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'develop') }}
           tags: |
